# permissions for end users to edit svngroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: svngroup-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: svn-operator
    app.kubernetes.io/part-of: svn-operator
    app.kubernetes.io/managed-by: kustomize
  name: svngroup-editor-role
rules:
- apiGroups:
  - svn.zhangyi.chat
  resources:
  - svngroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svn.zhangyi.chat
  resources:
  - svngroups/status
  verbs:
  - get
