# permissions for end users to view svnusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: svnuser-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: svn-operator
    app.kubernetes.io/part-of: svn-operator
    app.kubernetes.io/managed-by: kustomize
  name: svnuser-viewer-role
rules:
- apiGroups:
  - svn.zhangyi.chat
  resources:
  - svnusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - svn.zhangyi.chat
  resources:
  - svnusers/status
  verbs:
  - get
